/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.34
 * Generated at: 2023-11-23 08:59:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.ecommerce.pojo.*;
import com.ecommerce.dao.*;
import java.sql.*;
import java.util.*;
import com.ecommerce.pojo.*;
import com.ecommerce.dao.*;
import java.sql.*;
import java.util.*;

public final class admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/components/common_cs_js.jsp", Long.valueOf(1698763001036L));
    _jspx_dependants.put("/components/message.jsp", Long.valueOf(1656434539000L));
    _jspx_dependants.put("/components/navbar.jsp", Long.valueOf(1700729737544L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.ecommerce.pojo");
    _jspx_imports_packages.add("com.ecommerce.dao");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("    \n");
      out.write("    \n");
      out.write("    \n");
      out.write("    \n");
      out.write("    \n");
      out.write("\n");
      out.write("    ");

         User user2=(User)session.getAttribute("active-user");
         if(user2==null)
         {
        	 session.setAttribute("message","You are not logged in! Login first...");
		     response.sendRedirect("login.jsp");
		     return;
         }
         
         else
         {
             if(user2.getUserType().equals("normal"))
             {
            	 session.setAttribute("message","You are not Admin! Do not Access this...");
                 session.removeAttribute("active-user");
                 response.sendRedirect("login.jsp");
    		     return;
             }     
         }
    
      out.write("\n");
      out.write("    \n");
      out.write("    ");

        List<Category> li=new CategoryDaoImp().getAllCategory(); 
    
      out.write("\n");
      out.write("    \n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<style>\n");
      out.write(".custom-bg {\n");
      out.write("        background-color: #f0f0f0; /* Your desired background color */\n");
      out.write("    }\n");
      out.write("</style>\n");
      out.write("<meta charset=\"ISO-8859-1\">\n");
      out.write("<title>Admin Page-Precious Paw</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\" integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\"> \n");
      out.write("\n");
      out.write("<!-- JavaScript -->\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\" integrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\" integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\" integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\" crossorigin=\"anonymous\"></script>\n");
      out.write("\n");
      out.write("<script src=\"js/script.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write(" ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

     User user=(User)session.getAttribute("active-user"); 

      out.write('\n');
      out.write('\n');

         CategoryDaoImp cdao=new CategoryDaoImp();
         List<Category> cl=cdao.getAllCategory();

      out.write("\n");
      out.write("<div class=\"container-fluid bg-dark py-3 px-lg-5 d-none d-lg-block\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <div class=\"col-md-6 text-center text-lg-left mb-2 mb-lg-0\">\n");
      out.write("                <div class=\"d-inline-flex align-items-center\">\n");
      out.write("                    <a class=\"text-body pr-3\" href=\"\"><i class=\"fa fa-phone-alt mr-2\"></i>+91 9030992019</a>\n");
      out.write("                    <span class=\"text-body\">|</span>\n");
      out.write("                    <a class=\"text-body px-3\" href=\"\"><i class=\"fa fa-envelope mr-2\"></i>2100090151csit@gmail.com</a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-6 text-center text-lg-right\">\n");
      out.write("                <div class=\"d-inline-flex align-items-center\">\n");
      out.write("                    <a class=\"text-body px-3\" href=\"https://facebook.com/freewebsitecode/\">\n");
      out.write("                        <i class=\"fab fa-facebook-f\"></i>\n");
      out.write("                    </a>\n");
      out.write("                    <a class=\"text-body px-3\" href=\"https://freewebsitecode.com/\">\n");
      out.write("                        <i class=\"fab fa-twitter\"></i>\n");
      out.write("                    </a>\n");
      out.write("                    <a class=\"text-body px-3\" href=\"https://freewebsitecode.com/\">\n");
      out.write("                        <i class=\"fab fa-linkedin-in\"></i>\n");
      out.write("                    </a>\n");
      out.write("                    <a class=\"text-body px-3\" href=\"https://freewebsitecode.com/\">\n");
      out.write("                        <i class=\"fab fa-instagram\"></i>\n");
      out.write("                    </a>\n");
      out.write("                    <a class=\"text-body pl-3\" href=\"https://youtube.com/freewebsitecode/\">\n");
      out.write("                        <i class=\"fab fa-youtube\"></i>\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write(" \n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark custom-bg\">\n");
      out.write("\n");
      out.write("<div class=\"container-fluid\">\n");
      out.write("  <a class=\"navbar-brand\" href=\"index.jsp\"><h3><i>Precious Paw</i></h3></a>\n");
      out.write("  <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("    <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("  </button>\n");
      out.write("\n");
      out.write("  <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("    <ul class=\"navbar-nav mr-auto\">\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    ");

         if(user!=null)
         {
        	 
        	 String userType=user.getUserType();
        	 if(userType.equals("admin"))
        	 {
    
      out.write("\n");
      out.write("                 <li class=\"nav-item active\">\n");
      out.write("                    <a class=\"nav-link\" href=\"admin.jsp\"><b>Admin Page</b> <span class=\"sr-only\">(current)</span></a>\n");
      out.write("                 </li>\n");
      out.write("    ");

        	 }
         }
    
      out.write("\n");
      out.write("      <li class=\"nav-item active dropdown\">\n");
      out.write("        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n");
      out.write("         <b> Categories</b>\n");
      out.write("        </a>\n");
      out.write("        <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\n");
      out.write("          <a class=\"dropdown-item\" href=\"index.jsp?category=0\" >All</a>\n");
      out.write("               ");

                    for(Category c: cl)
                    {    	
               
      out.write(" \n");
      out.write("                         <a class=\"dropdown-item\" href=\"index.jsp?category=");
      out.print(c.getCategoryId() );
      out.write('"');
      out.write('>');
      out.print(c.getCategoryTitle() );
      out.write("</a>     \n");
      out.write("               ");

                    }
               
      out.write("\n");
      out.write("          \n");
      out.write("        </div>\n");
      out.write("      </li>\n");
      out.write("      <li class=\"nav-item active ml-2\" data-toggle=\"modal\" data-target=\".contactusmodal\">\n");
      out.write("          <a href=\"index2.jsp\" class=\"nav-item nav-link\">Home</a>\n");
      out.write("      </li>\n");
      out.write("      <li class=\"nav-item active ml-2\" data-toggle=\"modal\" data-target=\".aboutusmodal\">\n");
      out.write("          <div class=\"nav-link\" ><b>About us</b></div>\n");
      out.write("      </li>\n");
      out.write("      \n");
      out.write("      <li class=\"nav-item active ml-2\">\n");
      out.write("    <a class=\"nav-link\" href=\"contact.jsp\"><b>Contact us</b></a>\n");
      out.write("</li>\n");
      out.write("      <li class=\"nav-item active ml-2\">\n");
      out.write("          <a class=\"nav-link\" href=\"services.jsp\"><b>Services</b></a>\n");
      out.write("      </li>\n");
      out.write("      <li class=\"nav-item active ml-2\">\n");
      out.write("          <a class=\"nav-link\" href=\"organization.jsp\"><b>Organizations</b></a>\n");
      out.write("      </li>\n");
      out.write("     \n");
      out.write("    </ul>\n");
      out.write("    \n");
      out.write("    <form class=\"form-inline my-2 my-lg-0\" action=\"ProductOperationServlet\" method=\"post\">\n");
      out.write("      <input type=\"hidden\" name=\"action\" value=\"searchProduct\">\n");
      out.write("      <input class=\"form-control mr-sm-2\" type=\"text\" placeholder=\"Search product\" aria-label=\"Search\" size=\"40\" name=\"search\">\n");
      out.write("      <button type=\"submit\" class=\"btn btn-light\" style=\"color:#ff9800\"><b>Search</b></button>\n");
      out.write("    </form>\n");
      out.write("    \n");
      out.write("    ");

        if(user!=null)
        {
        	  
    
      out.write("\n");
      out.write("    \n");
      out.write("          <ul class=\"navbar-nav ml-auto\">\n");
      out.write("              \n");
      out.write("              ");

                  if(user.getUserType().equals("normal"))
                  {
              
      out.write("\n");
      out.write("                     <li class=\"nav-item active\">\n");
      out.write("    <a class=\"nav-link\" href=\"mycart.jsp\">\n");
      out.write("        <img src=\"images/cart.png\" style=\"width:23px;\" alt=\"img\">\n");
      out.write("        (");
      out.print( new CartDaoImp().totalCartByUserId(user.getUserId()) );
      out.write(")\n");
      out.write("    </a>\n");
      out.write("</li>\n");
      out.write("                     \n");
      out.write("                     <li class=\"nav-item active\" data-toggle=\"modal\" data-target=\"#showmyordermodal\">\n");
      out.write("                        <a class=\"nav-link\" href=\"#\"><b>My Orders</b></a>\n");
      out.write("                     </li>\n");
      out.write("              ");

                  }
              
      out.write("\n");
      out.write("          \n");
      out.write("             <li class=\"nav-item active\">\n");
      out.write("    <a class=\"nav-link\" href=\"myprofile.jsp\"><b>");
      out.print( user.getUserName());
      out.write("</b></a>\n");
      out.write("</li>\n");
      out.write("             \n");
      out.write("             <li class=\"nav-item active\">\n");
      out.write("             <div class=\"nav-link\" data-toggle=\"modal\" data-target=\".changepasswordmodal\"><b>change password</b></div>\n");
      out.write("             </li>  \n");
      out.write("      \n");
      out.write("             <li class=\"nav-item active\" data-toggle=\"modal\" data-target=\".logout-modal\">\n");
      out.write("             <a class=\"nav-link\" href=\"#\" ><b>Logout</b></a>\n");
      out.write("             </li>    \n");
      out.write("         </ul>\n");
      out.write("   \n");
      out.write("    ");

        }
    
        else
        {
    
      out.write("\n");
      out.write("    <ul class=\"navbar-nav ml-auto\">\n");
      out.write("       <li class=\"nav-item active\">\n");
      out.write("        <div class=\"nav-link\" data-toggle=\"modal\" data-target=\".forgetpasswordmodal\"><b>Forget password</b></div>\n");
      out.write("      </li> \n");
      out.write("    \n");
      out.write("      <li class=\"nav-item active\">\n");
      out.write("        <a class=\"nav-link\" href=\"register.jsp\"><b>Register</b></a>\n");
      out.write("      </li>  \n");
      out.write("      \n");
      out.write("      <li class=\"nav-item active\">\n");
      out.write("        <a class=\"nav-link\" href=\"login.jsp\"><b>Login</b></a>\n");
      out.write("      </li>    \n");
      out.write("    </ul>\n");
      out.write("    \n");
      out.write("    ");

        }
    
      out.write("     \n");
      out.write("    \n");
      out.write("  </div>\n");
      out.write("  </div>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("<!-- show profile modal -->\n");
      out.write("\n");
      out.write("<div class=\"modal fade\" id=\"showprofilemodal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLongTitle\" aria-hidden=\"true\">\n");
      out.write("  <div class=\"modal-dialog modal-lg\" role=\"document\">\n");
      out.write("    <div class=\"modal-content\">\n");
      out.write("      <div class=\"modal-header custom-bg text-white text-center\">\n");
      out.write("        <h5 class=\"modal-title\" id=\"exampleModalLongTitle\" >MY PROFILE</h5>\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\n");
      out.write("        </button>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"modal-body\">\n");
      out.write("          <form >\n");
      out.write("         \n");
      out.write("         <div class=\"container text-center\">\n");
      out.write("                   <img style=\"max-width:200px\" class=\"img-fluid rounded-circle\" src=\"userProfilePic/");
if(user!=null){ 
      out.print(user.getUserPic() );
} 
      out.write("\" alt=\"users_pic\" >\n");
      out.write("         </div> \n");
      out.write("         \n");
      out.write("  <div class=\"form-row mt-3\">\n");
      out.write("    <div class=\"form-group col-md-4\">\n");
      out.write("      <label for=\"inputEmail4\">Name</label>\n");
      out.write("      <input type=\"text\" class=\"form-control\" id=\"inputEmail4\" value=\"");
if(user!=null){ 
      out.print(user.getUserName() );
} 
      out.write("\" readonly>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"form-group col-md-4\">\n");
      out.write("      <label for=\"inputPassword4\">Email</label>\n");
      out.write("      <input type=\"email\" class=\"form-control\" id=\"inputPassword4\" value=\"");
if(user!=null){ 
      out.print(user.getUserEmail() );
} 
      out.write("\" readonly>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"form-group col-md-4\">\n");
      out.write("      <label for=\"inputPassword4\">Phone</label>\n");
      out.write("      <input type=\"text\" class=\"form-control\" id=\"inputPassword4\" value=\"");
if(user!=null){ 
      out.print(user.getUserPhone() );
} 
      out.write("\" readonly>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("  <div class=\"form-group\">\n");
      out.write("    <label for=\"inputAddress\">Address</label>\n");
      out.write("    <textarea class=\"form-control\" id=\"inputAddress\" placeholder=\"1234 Main St\" rows=\"3\" readonly>");
if(user!=null){ 
      out.print(user.getUserAddress() );
} 
      out.write("</textarea>\n");
      out.write("  </div>\n");
      out.write(" \n");
      out.write("  <div class=\"container text-center\">\n");
      out.write("       <button type=\"button\" class=\"btn custom-bg text-light\" data-dismiss=\"modal\">Close</button>\n");
      out.write("  </div>   \n");
      out.write("</form>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!--  -->\n");
      out.write("\n");
      out.write("<!-- show my cart modal -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!--  -->\n");
      out.write("\n");
      out.write("<!-- show my order modal -->\n");
      out.write("\n");
      out.write("<div class=\"modal fade\" id=\"showmyordermodal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLongTitle\" aria-hidden=\"true\">\n");
      out.write("  <div class=\"modal-dialog modal-lg\" role=\"document\">\n");
      out.write("    <div class=\"modal-content\">\n");
      out.write("      <div class=\"modal-header custom-bg text-white text-center\">\n");
      out.write("        <h5 class=\"modal-title\" id=\"exampleModalLongTitle\" >MY ORDERS</h5>\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\n");
      out.write("        </button>\n");
      out.write("      </div>\n");
      out.write("     ");

      if(user!=null)
      {
    	  List<Order> l=new OrderDaoImp().getOrderByUserId(user.getUserId());
    	 
     
      out.write("\n");
      out.write("      <div class=\"modal-body\">\n");
      out.write("        \n");
      out.write("        ");

            if(l.isEmpty())
            {
        
      out.write("\n");
      out.write("        <div class=\"text-center\">\n");
      out.write("        <h1>NO ORDERS MADE BY YOU !!</h1>\n");
      out.write("        <hr>\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Close</button>\n");
      out.write("        </div>\n");
      out.write("        ");

            }
        
            else
            {
            	
            	
        
      out.write("\n");
      out.write("        <div class=\"table-responsive\">\n");
      out.write("          <table class=\"table\">\n");
      out.write("  <thead class=\"custom-bg text-white\">\n");
      out.write("    <tr>\n");
      out.write("      <th scope=\"col\">Product Image</th>\n");
      out.write("      <th scope=\"col\">Product Title</th> \n");
      out.write("      <th scope=\"col\">Product Description</th>    \n");
      out.write("      <th scope=\"col\">Quantity</th>\n");
      out.write("      <th scope=\"col\">Price</th>\n");
      out.write("      <th scope=\"col\">Ordered Date</th>\n");
      out.write("      <th scope=\"col\">Delivery Date</th>\n");
      out.write("    </tr>\n");
      out.write("  </thead>\n");
      out.write("  \n");
      out.write(" \n");
      out.write("  \n");
      out.write("  <tbody>\n");
      out.write("   ");

      OrderDaoImp odao=new OrderDaoImp();
      
   
      out.write("\n");
      out.write("  \n");
      out.write("   ");

      for(Order o:l)
      {
    	  int productId=o.getProdctId();
    	  Product p=new ProductDaoImp().getProductById(productId);
   
      out.write("\n");
      out.write("    <tr class=\"text-center\">\n");
      out.write("      <td><img style=\"max-height:100px;max-width:70px;width:auto;\" class=\"img-fluid mx-auto d-block\" src=\"productImages/");
      out.print(p.getProductPhoto() );
      out.write("\" alt=\"users_pic\" ></td>\n");
      out.write("      <td class=\"mid-align\">");
      out.print(p.getProductTitle() );
      out.write("</td>\n");
      out.write("      <td class=\"mid-align\">");
      out.print(p.getProductDescription() );
      out.write("</td>\n");
      out.write("      <td class=\"mid-align\">");
      out.print(o.getQuantity() );
      out.write("</td>\n");
      out.write("      <td class=\"mid-align\">");
      out.print(o.getPrice() );
      out.write("</td>\n");
      out.write("      <td class=\"mid-align\">");
      out.print(o.getOrderesDate() );
      out.write("</td>\n");
      out.write("      <td class=\"mid-align\">");
if(o.getDeliveryDate().equals("0")){ 
      out.write("<span style=\"color:red;\"> ");
      out.print("processing..");
      out.write("</span>    ");
} else { 
      out.write(' ');
      out.print(o.getDeliveryDate() );
} 
      out.write("</td>\n");
      out.write("    </tr>\n");
      out.write("    ");

      }
    
      out.write("\n");
      out.write("  </tbody>\n");
      out.write(" \n");
      out.write("  \n");
      out.write("</table>\n");
      out.write("<hr>\n");
      out.write("\n");
      out.write("<div class=\"text-right\">\n");
      out.write("    <p style=\"font-size:25px;\"><b>Total Price :&#8377;");
      out.print(new OrderDaoImp().totalOrderPrice(user.getUserId()) );
      out.write("/- </b></p> \n");
      out.write("</div>\n");
      out.write("<hr>\n");
      out.write("\n");
      out.write("      <button type=\"button\" class=\"btn btn-secondary ml-5\" data-dismiss=\"modal\">Close</button>\n");
      out.write("\n");
      out.write("       ");

            }
       
      out.write("\n");
      out.write("         \n");
      out.write("      </div>\n");
      out.write("  ");

           
      }
  
      out.write("\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!--  -->\n");
      out.write("\n");
      out.write("<!-- Logout modal -->\n");
      out.write("\n");
      out.write("<div class=\"modal fade logout-modal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"mySmallModalLabel\" aria-hidden=\"true\">\n");
      out.write("  <div class=\"modal-dialog modal-sm\">\n");
      out.write("    <div class=\"modal-content\">\n");
      out.write("    <div class=\"modal-header custom-bg text-white text-center\">\n");
      out.write("        <h5 class=\"modal-title\" id=\"exampleModalLongTitle\" >Log Out</h5>\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\n");
      out.write("        </button>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"modal-body text-center\">\n");
      out.write("            <h5>Do you want to logout?</h5>\n");
      out.write("          \n");
      out.write("          <div class=\"text-center\">\n");
      out.write("            <a href=\"LoginServlet\"><button type=\"button\" class=\"btn custom-bg text-white\">Yes</button></a>\n");
      out.write("            <button type=\"button\" class=\"btn btn-secondary ml-5\" data-dismiss=\"modal\">No</button>\n");
      out.write("          </div> \n");
      out.write("     </div>     \n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!-- *********** -->\n");
      out.write("\n");
      out.write("<!-- About us modal -->\n");
      out.write("\n");
      out.write("<div class=\"modal fade aboutusmodal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"mySmallModalLabel\" aria-hidden=\"true\">\n");
      out.write("  <div class=\"modal-dialog modal-lg\">\n");
      out.write("    <div class=\"modal-content\">\n");
      out.write("       <div class=\"modal-header custom-bg text-white text-center\">\n");
      out.write("        <h5 class=\"modal-title\" id=\"exampleModalLongTitle\" >About Us</h5>\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\n");
      out.write("        </button>\n");
      out.write("      </div> \n");
      out.write("      <div class=\"modal-body\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("        <p style=\"font-size:20px;\">\n");
      out.write("          <b>\n");
      out.write("              Welcome to our pet-centric platform! A pet website is a virtual haven where you can explore a world dedicated to the well-being, trade, and interactions involving our beloved furry companions.\n");
      out.write("\n");
      out.write("Pets, from our loyal dogs to our enchanting cats, bring immense joy to our lives. This website celebrates the beauty of pet ownership, offering avenues for the exchange of services, information, and connections within the pet-loving community.\n");
      out.write("\n");
      out.write("Just like the age-old barter system and trade that has been a part of human history, pet enthusiasts and owners have always sought ways to connect and provide for their furry friends. Whether it's pet services, sharing pet-related knowledge, or finding that perfect toy, our platform facilitates this exchange.\n");
      out.write("\n");
      out.write("Transactions, both locally and globally, have been the backbone of the pet community. Now, in the digital realm, we embrace this legacy, creating a space where pet lovers can come together, trade, and seek services.\n");
      out.write("\n");
      out.write("However, as we step into the digital sphere, we're acutely aware of the importance of data privacy. Stringent data protection laws govern our operations. Prior to engaging in our pet-oriented venture, it's crucial to understand and comply with all the legal policies necessary to safeguard the data and privacy of our users.\n");
      out.write("\n");
      out.write("Our pet-centric platform aims to merge the joy of pet ownership with a secure, user-friendly online experience, fostering a community that values the love and care for our adorable companions.\n");
      out.write("          </b>\n");
      out.write("        </p>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"modal-footer\">\n");
      out.write("       <div class=\"text-center\">\n");
      out.write("        <button type=\"button\" class=\"btn custom-bg text-white\" data-dismiss=\"modal\">Close</button>\n");
      out.write("       </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("<!-- ********** -->\n");
      out.write("\n");
      out.write("<!-- Contact us modal -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- change password modal -->\n");
      out.write("\n");
      out.write("<div class=\"modal fade changepasswordmodal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLongTitle\" aria-hidden=\"true\">\n");
      out.write("  <div class=\"modal-dialog\" role=\"document\">\n");
      out.write("    <div class=\"modal-content\">\n");
      out.write("      <div class=\"modal-header custom-bg text-white text-center\">\n");
      out.write("        <h5 class=\"modal-title\" id=\"exampleModalLongTitle\" >Change Password</h5>\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\n");
      out.write("        </button>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"modal-body\">\n");
      out.write("          <form action=\"LoginServlet\" method=\"post\">\n");
      out.write("          <input type=\"hidden\" name=\"action\" value=\"changePassword\">\n");
      out.write("         \n");
      out.write("  <div class=\"form\">\n");
      out.write(" \n");
      out.write("    <div class=\"form-group \">\n");
      out.write("      <label for=\"inputPassword4\">Email</label>\n");
      out.write("      <input type=\"email\" class=\"form-control\" id=\"inputPassword4\" value=\"");
if(user!=null){ 
      out.print(user.getUserEmail() );
} 
      out.write("\" readonly>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"form-group\">\n");
      out.write("      <label for=\"inputPassword4\">Password</label>\n");
      out.write("      <input type=\"password\" class=\"form-control\" id=\"pass\" name=\"pass\" >\n");
      out.write("    </div>\n");
      out.write("    <div class=\"form-group\">\n");
      out.write("      <label for=\"inputPassword4\">Confirm Password</label>\n");
      out.write("      <input type=\"password\" class=\"form-control\" id=\"cpass\" name=\"cpass\">\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write(" \n");
      out.write("  <div class=\"container text-center\">\n");
      out.write("       \n");
      out.write("       <input type=\"submit\" class=\"btn custom-bg text-light\" value=\"Change\">\n");
      out.write("       <button type=\"button\" class=\"btn custom-bg text-light ml-5\" data-dismiss=\"modal\">Close</button>\n");
      out.write("                                      \n");
      out.write("  </div>   \n");
      out.write("</form>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!--  -->\n");
      out.write("\n");
      out.write("<!-- forget password modal -->\n");
      out.write("\n");
      out.write("<div class=\"modal fade forgetpasswordmodal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLongTitle\" aria-hidden=\"true\">\n");
      out.write("  <div class=\"modal-dialog\" role=\"document\">\n");
      out.write("    <div class=\"modal-content\">\n");
      out.write("      <div class=\"modal-header custom-bg text-white text-center\">\n");
      out.write("        <h5 class=\"modal-title\" id=\"exampleModalLongTitle\" >Forget Password</h5>\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\n");
      out.write("        </button>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"modal-body\">\n");
      out.write("          <form action=\"LoginServlet\" method=\"post\">\n");
      out.write("          <input type=\"hidden\" name=\"action\" value=\"forgetPassword\">\n");
      out.write("         \n");
      out.write("  <div class=\"form\">\n");
      out.write(" \n");
      out.write("    <div class=\"form-group \">\n");
      out.write("      <label for=\"inputPassword4\">Email</label>\n");
      out.write("      <input type=\"email\" class=\"form-control\" id=\"email\" name=\"email\">\n");
      out.write("    </div>\n");
      out.write("    <div class=\"form-group \">\n");
      out.write("      <label for=\"inputPassword4\">Phone</label>\n");
      out.write("      <input type=\"text\" class=\"form-control\" id=\"phone\" name=\"phone\">\n");
      out.write("    </div>\n");
      out.write("    <div class=\"form-group\">\n");
      out.write("      <label for=\"inputPassword4\">Password</label>\n");
      out.write("      <input type=\"password\" class=\"form-control\" id=\"pass\" name=\"pass\" >\n");
      out.write("    </div>\n");
      out.write("    <div class=\"form-group\">\n");
      out.write("      <label for=\"inputPassword4\">Confirm Password</label>\n");
      out.write("      <input type=\"password\" class=\"form-control\" id=\"cpass\" name=\"cpass\">\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write(" \n");
      out.write("  <div class=\"container text-center\">\n");
      out.write("       \n");
      out.write("       <input type=\"submit\" class=\"btn custom-bg text-light\" value=\"Change\">\n");
      out.write("       <button type=\"button\" class=\"btn custom-bg text-light ml-5\" data-dismiss=\"modal\">Close</button>\n");
      out.write("                                      \n");
      out.write("  </div>   \n");
      out.write("</form>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!--  -->\n");
      out.write("\n");
      out.write("\n");
      out.write(" \n");
      out.write(" <div class=\"container admin mt-2\">\n");
      out.write("     ");

    String message=(String)session.getAttribute("message");
    if(message!=null)
    {
    	//out.print(message);

      out.write("\n");
      out.write("    <div class=\"alert alert-success alert-dismissible fade show text-center\" role=\"alert\">\n");
      out.write("        <strong>");
      out.print(message );
      out.write("</strong>\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-label=\"Close\">\n");
      out.write("        <span aria-hidden=\"true\">&times;</span>\n");
      out.write("        </button>\n");
      out.write("   </div>\n");
    		
    	session.removeAttribute("message");
    }

      out.write("\n");
      out.write("      <div class=\"row mt-3\">\n");
      out.write("           <div class=\"col-md-4\">\n");
      out.write("                 <div class=\"card hover\" data-toggle=\"modal\" data-target=\"#show-users-modal\">\n");
      out.write("                     <div class=\"card-body text-center\">\n");
      out.write("                         <div class=\"container\">\n");
      out.write("                             <img style=\"max-width:120px\" class=\"img-fluid rounded-circle\" src=\"images/user.png\" alt=\"users_pic\" >\n");
      out.write("                         </div>\n");
      out.write("                         <h1>");
      out.print(new UserDaoImp().getTotalUser() );
      out.write("</h1>\n");
      out.write("                         <h2 class=\"text-uppercase text-muted\">Users</h2>\n");
      out.write("                     </div>\n");
      out.write("                 </div>\n");
      out.write("           </div>\n");
      out.write("           \n");
      out.write("           <div class=\"col-md-4\">\n");
      out.write("                  <div class=\"card hover\" data-toggle=\"modal\" data-target=\"#show-category-modal\">\n");
      out.write("                     <div class=\"card-body text-center\">\n");
      out.write("                          <div class=\"container\">\n");
      out.write("                             <img style=\"max-width:120px\" class=\"img-fluid rounded-circle\" src=\"images/category.png\" alt=\"users_pic\" >\n");
      out.write("                         </div>\n");
      out.write("                          <h1>");
      out.print(new CategoryDaoImp().getTotalCategory() );
      out.write("</h1>\n");
      out.write("                          <h2 class=\"text-uppercase text-muted\">Total Category</h2>\n");
      out.write("                     </div>\n");
      out.write("                 </div>\n");
      out.write("           </div>\n");
      out.write("           \n");
      out.write("           <div class=\"col-md-4\">\n");
      out.write("                  <div class=\"card hover\" data-toggle=\"modal\" data-target=\"#show-product-modal\">\n");
      out.write("                     <div class=\"card-body text-center\">\n");
      out.write("                           <div class=\"container\">\n");
      out.write("                             <img style=\"max-width:120px\" class=\"img-fluid rounded-circle\" src=\"images/product.png\" alt=\"users_pic\" >\n");
      out.write("                           </div>\n");
      out.write("                           <h1>");
      out.print(new ProductDaoImp().getTotalProduct() );
      out.write("</h1>\n");
      out.write("                           <h2 class=\"text-uppercase text-muted\">Total Products</h2>\n");
      out.write("                     </div>\n");
      out.write("                 </div>\n");
      out.write("           </div>\n");
      out.write("      </div>\n");
      out.write("      \n");
      out.write("      <div class=\"row mt-3\">\n");
      out.write("    <div class=\"col-md-4\">\n");
      out.write("        <a href=\"torders.jsp\" class=\"card hover\">\n");
      out.write("            <div class=\"card-body text-center\">\n");
      out.write("                <div class=\"container\">\n");
      out.write("                    <img style=\"max-width:120px\" class=\"img-fluid rounded-circle\" src=\"images/check.png\" alt=\"users_pic\">\n");
      out.write("                </div>\n");
      out.write("                <h1 class=\"text-lowercase text-muted\">");
      out.print(new OrderDaoImp().totalOrdersCount() );
      out.write("</h1>\n");
      out.write("                <h2 class=\"text-uppercase text-muted\">Total Orders</h2>\n");
      out.write("            </div>\n");
      out.write("        </a>\n");
      out.write("    </div>\n");
      out.write("           \n");
      out.write("           <div class=\"col-md-4\">\n");
      out.write("                  <div class=\"card hover\" data-toggle=\"modal\" data-target=\"#add-category-modal\">\n");
      out.write("                     <div class=\"card-body text-center\">\n");
      out.write("                          <div class=\"container md-5\">\n");
      out.write("                             <img style=\"max-width:120px\" class=\"img-fluid rounded-circle\" src=\"images/addCategory.jpg\" alt=\"users_pic\" >\n");
      out.write("                         </div>\n");
      out.write("                          <p class=\"text-lowercase text-muted mt-2 \" style=\"font-size:22px\">click to add category</p>\n");
      out.write("                          <h2 class=\"text-uppercase text-muted mt-1\">Add Category</h2>\n");
      out.write("                     </div>\n");
      out.write("                 </div>\n");
      out.write("           </div>\n");
      out.write("           \n");
      out.write("           <div class=\"col-md-4\">\n");
      out.write("                  <div class=\"card hover\" data-toggle=\"modal\" data-target=\"#add-product-modal\">\n");
      out.write("                     <div class=\"card-body text-center\">\n");
      out.write("                          <div class=\"container\">\n");
      out.write("                             <img style=\"max-width:120px\" class=\"img-fluid rounded-circle\" src=\"images/addproduct.png\" alt=\"users_pic\" >\n");
      out.write("                         </div>\n");
      out.write("                          <p class=\"text-lowercase text-muted mt-2 \" style=\"font-size:22px\">click to add product</p>\n");
      out.write("                          <h2 class=\"text-uppercase text-muted\">Add Product</h2>\n");
      out.write("                     </div>\n");
      out.write("                 </div>\n");
      out.write("           </div>\n");
      out.write("           \n");
      out.write("      </div>\n");
      out.write("      \n");
      out.write(" </div> \n");
      out.write("  \n");
      out.write("<!-- add category modal -->\n");
      out.write("     \n");
      out.write("<div class=\"modal fade\" id=\"add-category-modal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLongTitle\" aria-hidden=\"true\">\n");
      out.write("  <div class=\"modal-dialog modal-lg\" role=\"document\">\n");
      out.write("    <div class=\"modal-content\">\n");
      out.write("      <div class=\"modal-header custom-bg text-white\">\n");
      out.write("        <h5 class=\"modal-title\" id=\"exampleModalLongTitle\" >Fill category details.</h5>\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\n");
      out.write("        </button>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"modal-body\">\n");
      out.write("          <form action=\"ProductOperationServlet\" method=\"post\">\n");
      out.write("               <input type=\"hidden\" name=\"action\" value=\"addCategory\">\n");
      out.write("               <div class=\"form-group\">\n");
      out.write("                   <input type=\"text\" class=\"form-control\" name=\"categoryTitle\" placeholder=\"Enter Category Title here\" required>\n");
      out.write("               </div>\n");
      out.write("               \n");
      out.write("               <div class=\"form-group\">\n");
      out.write("                   <textarea style=\"height:250px\" class=\"form-control\" name=\"categoryDescription\" placeholder=\"Enter Category Description here\" required></textarea>\n");
      out.write("               </div>\n");
      out.write("               \n");
      out.write("               <div class=\"container text-center\">\n");
      out.write("                   <button class=\"btn custom-bg text-white\">Add Category</button>\n");
      out.write("                   <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Close</button>\n");
      out.write("               </div>   \n");
      out.write("          </form>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("      \n");
      out.write("      \n");
      out.write("  <!-- end add category modal -->\n");
      out.write("  \n");
      out.write("  <!-- add product modal -->\n");
      out.write("     \n");
      out.write("<div class=\"modal fade\" id=\"add-product-modal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLongTitle\" aria-hidden=\"true\">\n");
      out.write("  <div class=\"modal-dialog modal-lg\" role=\"document\">\n");
      out.write("    <div class=\"modal-content\">\n");
      out.write("      <div class=\"modal-header custom-bg text-white\">\n");
      out.write("        <h5 class=\"modal-title\" id=\"exampleModalLongTitle\" >Add Product details.</h5>\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\n");
      out.write("        </button>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"modal-body\">\n");
      out.write("          <form action=\"ProductOperationServlet\" method=\"post\" enctype=\"multipart/form-data\">\n");
      out.write("               <input type=\"hidden\" name=\"action\" value=\"addProduct\">\n");
      out.write("               <div class=\"form-group\">\n");
      out.write("                   <input type=\"text\" class=\"form-control\" name=\"productTitle\" placeholder=\"Enter Product Title here\" required>\n");
      out.write("               </div>\n");
      out.write("               \n");
      out.write("               <div class=\"form-group\">\n");
      out.write("                   <textarea style=\"height:150px\" class=\"form-control\" name=\"productDescription\" placeholder=\"Enter Product Description here\" required></textarea>\n");
      out.write("               </div>\n");
      out.write("               \n");
      out.write("               <div class=\"form-group\">\n");
      out.write("                   <input type=\"number\" class=\"form-control\" name=\"productPrice\" placeholder=\"Enter Product Price here\" required>\n");
      out.write("               </div>\n");
      out.write("               \n");
      out.write("               <div class=\"form-group\">\n");
      out.write("                   <input type=\"text\" class=\"form-control\" name=\"productQuantity\" placeholder=\"Enter Product Quantity here\" required>\n");
      out.write("               </div>\n");
      out.write("               \n");
      out.write("               <div class=\"form-group\">\n");
      out.write("                   <input type=\"text\" class=\"form-control\" name=\"productDiscount\" placeholder=\"Enter Product Discount in (%)\" required>\n");
      out.write("               </div>\n");
      out.write("               \n");
      out.write("               <div class=\"form-group\">\n");
      out.write("                   <select name=\"productCategoryId\" class=\"form-control\">\n");
      out.write("                       <option value=\"\">Select Category</option>\n");
      out.write("                       ");

                           for(Category category:li)
                           {
                       
      out.write("\n");
      out.write("                       <option value=\"");
      out.print(category.getCategoryId());
      out.write('"');
      out.write('>');
      out.print(category.getCategoryTitle() );
      out.write("</option>\n");
      out.write("                       ");

                           }
                       
      out.write("\n");
      out.write("                   </select>\n");
      out.write("               </div>\n");
      out.write("               \n");
      out.write("               <div class=\"form-group\">\n");
      out.write("                   <label>Select Product Pic</label><br>\n");
      out.write("                   <input type=\"file\" class=\"form-control\" name=\"productPic\" required>\n");
      out.write("               </div>\n");
      out.write("               \n");
      out.write("               <div class=\"container text-center\">\n");
      out.write("                   <button class=\"btn custom-bg text-white\">Add Product</button>\n");
      out.write("                   <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Close</button>\n");
      out.write("               </div>   \n");
      out.write("          </form>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>   \n");
      out.write("   \n");
      out.write("  <!-- end add product modal -->\n");
      out.write("  \n");
      out.write("  <!-- show users modal -->\n");
      out.write("     \n");
      out.write("<div class=\"modal fade\" id=\"show-users-modal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLongTitle\" aria-hidden=\"true\">\n");
      out.write("  <div class=\"modal-dialog modal-lg\" role=\"document\">\n");
      out.write("    <div class=\"modal-content\">\n");
      out.write("      <div class=\"modal-header custom-bg text-white text-center\">\n");
      out.write("        <h5 class=\"modal-title\" id=\"exampleModalLongTitle\" >Total Users</h5>\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\n");
      out.write("        </button>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"modal-body\">\n");
      out.write("      <div class=\"table-responsive\">\n");
      out.write("          <table class=\"table\">\n");
      out.write("  <thead class=\"custom-bg text-white\">\n");
      out.write("    <tr>\n");
      out.write("      <th scope=\"col\">User Id</th>\n");
      out.write("      <th scope=\"col\">Photo</th>\n");
      out.write("      <th scope=\"col\">Name</th>\n");
      out.write("      <th scope=\"col\">Email</th>\n");
      out.write("      <th scope=\"col\">Mobile</th>\n");
      out.write("      <th scope=\"col\">Address</th>\n");
      out.write("    </tr>\n");
      out.write("  </thead>\n");
      out.write("  <tbody>\n");
      out.write("   ");

      UserDaoImp udao=new UserDaoImp();
      List<User> l=udao.getAllUser("normal");
   
      out.write("\n");
      out.write("  \n");
      out.write("   ");

      for(User u:l)
      {
   
      out.write("\n");
      out.write("    <tr>\n");
      out.write("      <th scope=\"row\" class=\"mid-align\">");
      out.print(u.getUserId() );
      out.write("</th>\n");
      out.write("      <td><img style=\"max-width:70px\" class=\"img-fluid rounded-circle\" src=\"userProfilePic/");
      out.print(u.getUserPic() );
      out.write("\" alt=\"users_pic\" ></td>\n");
      out.write("      <td class=\"mid-align\">");
      out.print(u.getUserName() );
      out.write("</td>\n");
      out.write("      <td class=\"mid-align\">");
      out.print(u.getUserEmail() );
      out.write("</td>\n");
      out.write("      <td class=\"mid-align\">");
      out.print(u.getUserPhone() );
      out.write("</td>\n");
      out.write("      <td class=\"mid-align\">");
      out.print(u.getUserAddress() );
      out.write("</td>\n");
      out.write("    </tr>\n");
      out.write("    ");

      }
    
      out.write("\n");
      out.write("  </tbody>\n");
      out.write("</table>\n");
      out.write("</div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("        \n");
      out.write("<!-- end of show users modal -->\n");
      out.write("\n");
      out.write("<!-- show category modal -->\n");
      out.write("\n");
      out.write("<div class=\"modal fade\" id=\"show-category-modal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLongTitle\" aria-hidden=\"true\">\n");
      out.write("  <div class=\"modal-dialog modal-lg\" role=\"document\">\n");
      out.write("    <div class=\"modal-content\">\n");
      out.write("      <div class=\"modal-header custom-bg text-white text-center\">\n");
      out.write("        <h5 class=\"modal-title\" id=\"exampleModalLongTitle\" >Total Category</h5>\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\n");
      out.write("        </button>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"modal-body\">\n");
      out.write("      <div class=\"table-responsive\">\n");
      out.write("          <table class=\"table\">\n");
      out.write("  <thead class=\"custom-bg text-white\">\n");
      out.write("    <tr>\n");
      out.write("      <th scope=\"col\">Category Id</th>\n");
      out.write("      <th scope=\"col\">Category Name</th>\n");
      out.write("      <th scope=\"col\">Category Description</th>\n");
      out.write("      <th scope=\"col\">Action</th>\n");
      out.write("    </tr>\n");
      out.write("  </thead>\n");
      out.write("  <tbody>\n");
      out.write("   ");

      CategoryDaoImp cd=new CategoryDaoImp();
      List<Category> lc=cd.getAllCategory();
   
      out.write("\n");
      out.write("  \n");
      out.write("   ");

      for(Category c:lc)
      {
   
      out.write("\n");
      out.write("    <tr>\n");
      out.write("      <td class=\"mid-align\">");
      out.print(c.getCategoryId() );
      out.write("</td>\n");
      out.write("      <td class=\"mid-align\">");
      out.print(c.getCategoryTitle() );
      out.write("</td>\n");
      out.write("      <td class=\"mid-align\">");
      out.print(c.getCategoryDescription() );
      out.write("</td>\n");
      out.write("      <td class=\"mid-align\"><a href=\"ProductOperationServlet?categoryId=");
      out.print(c.getCategoryId());
      out.write("&action=deleteCategory\"><input type=\"submit\" class=\"btn btn-danger\" value=\"Delete\"></a></td>\n");
      out.write("    </tr>\n");
      out.write("    ");

      }
    
      out.write("\n");
      out.write("  </tbody>\n");
      out.write("</table>\n");
      out.write("</div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!-- ********************* -->\n");
      out.write("\n");
      out.write("<!-- show Product modal -->\n");
      out.write("\n");
      out.write("<div class=\"modal fade\" id=\"show-product-modal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLongTitle\" aria-hidden=\"true\">\n");
      out.write("  <div class=\"modal-dialog modal-lg\" role=\"document\">\n");
      out.write("    <div class=\"modal-content\">\n");
      out.write("      <div class=\"modal-header custom-bg text-white text-center\">\n");
      out.write("        <h5 class=\"modal-title\" id=\"exampleModalLongTitle\" >Total Product</h5>\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\n");
      out.write("        </button>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"modal-body\">\n");
      out.write("      <div class=\"table-responsive\">\n");
      out.write("          <table class=\"table\">\n");
      out.write("  <thead class=\"custom-bg text-white\">\n");
      out.write("    <tr>\n");
      out.write("      <th scope=\"col\">Product Name</th>\n");
      out.write("      <th scope=\"col\">Product Image</th>\n");
      out.write("      <th scope=\"col\">Product Description</th>\n");
      out.write("      <th scope=\"col\">Product Category</th>\n");
      out.write("      <th scope=\"col\">Product Price</th>\n");
      out.write("      <th scope=\"col\">Product Discount</th>\n");
      out.write("      <th scope=\"col\">Product Quantity</th>\n");
      out.write("    </tr>\n");
      out.write("  </thead>\n");
      out.write("  <tbody>\n");
      out.write("   ");

      ProductDaoImp pd=new ProductDaoImp();
      List<Product> lp=pd.getAllProduct();
      CategoryDaoImp c=new CategoryDaoImp();
   
      out.write("\n");
      out.write("  \n");
      out.write("   ");

      for(Product p:lp)
      {
   
      out.write("\n");
      out.write("    <tr>\n");
      out.write("      <td class=\"mid-align\">");
      out.print(p.getProductTitle() );
      out.write("</td>\n");
      out.write("      <td class=\"mid-align\"><img style=\"max-width:70px\" class=\"img-fluid\" src=\"productImages/");
      out.print(p.getProductPhoto() );
      out.write("\" alt=\"users_pic\" ></td>\n");
      out.write("      <td class=\"mid-align\">");
      out.print(p.getProductDescription());
      out.write("</td>\n");
      out.write("       <td class=\"mid-align\">");
      out.print(c.getCategoryNameById(p.getCategoryId()) );
      out.write("</td>\n");
      out.write("      <td class=\"mid-align\">");
      out.print(p.getProductPrice() );
      out.write("</td>\n");
      out.write("      <td class=\"mid-align\">");
      out.print(p.getProductDiscount() );
      out.write("</td>\n");
      out.write("      <td class=\"mid-align\">");
      out.print(p.getProductQuantity() );
      out.write("</td>\n");
      out.write("    </tr>\n");
      out.write("    ");

      }
    
      out.write("\n");
      out.write("  </tbody>\n");
      out.write("</table>\n");
      out.write("</div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!-- ********************* -->\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"container-fluid bg-light mt-5 py-5 custom-bg\">\n");
      out.write("        <div class=\"container pt-5\">\n");
      out.write("            <div class=\"row g-5\">\n");
      out.write("                <div class=\"col-lg-3 col-md-6\">\n");
      out.write("                    <h5 class=\"text-uppercase border-start border-5 border-primary ps-3 mb-4\">Get In Touch</h5>\n");
      out.write("                    <p class=\"mb-4\">No dolore ipsum accusam no lorem. Invidunt sed clita kasd clita et et dolor sed dolor</p>\n");
      out.write("                    <p class=\"mb-2\"><i class=\"bi bi-geo-alt text-primary me-2\"></i>123 Street, New York, USA</p>\n");
      out.write("                    <p class=\"mb-2\"><i class=\"bi bi-envelope-open text-primary me-2\"></i>info@example.com</p>\n");
      out.write("                    <p class=\"mb-0\"><i class=\"bi bi-telephone text-primary me-2\"></i>+012 345 67890</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-lg-3 col-md-6\">\n");
      out.write("                    <h5 class=\"text-uppercase border-start border-5 border-primary ps-3 mb-4\">Quick Links</h5>\n");
      out.write("                    <div class=\"d-flex flex-column justify-content-start\">\n");
      out.write("                        <a class=\"text-body mb-2\" href=\"#\"><i class=\"bi bi-arrow-right text-primary me-2\"></i>Home</a>\n");
      out.write("                        <a class=\"text-body mb-2\" href=\"#\"><i class=\"bi bi-arrow-right text-primary me-2\"></i>About Us</a>\n");
      out.write("                        <a class=\"text-body mb-2\" href=\"#\"><i class=\"bi bi-arrow-right text-primary me-2\"></i>Our Services</a>\n");
      out.write("                        <a class=\"text-body mb-2\" href=\"#\"><i class=\"bi bi-arrow-right text-primary me-2\"></i>Meet The Team</a>\n");
      out.write("                        <a class=\"text-body mb-2\" href=\"#\"><i class=\"bi bi-arrow-right text-primary me-2\"></i>Latest Blog</a>\n");
      out.write("                        <a class=\"text-body\" href=\"#\"><i class=\"bi bi-arrow-right text-primary me-2\"></i>Contact Us</a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-lg-3 col-md-6\">\n");
      out.write("                    <h5 class=\"text-uppercase border-start border-5 border-primary ps-3 mb-4\">Popular Links</h5>\n");
      out.write("                    <div class=\"d-flex flex-column justify-content-start\">\n");
      out.write("                        <a class=\"text-body mb-2\" href=\"#\"><i class=\"bi bi-arrow-right text-primary me-2\"></i>Home</a>\n");
      out.write("                        <a class=\"text-body mb-2\" href=\"#\"><i class=\"bi bi-arrow-right text-primary me-2\"></i>About Us</a>\n");
      out.write("                        <a class=\"text-body mb-2\" href=\"#\"><i class=\"bi bi-arrow-right text-primary me-2\"></i>Our Services</a>\n");
      out.write("                        <a class=\"text-body mb-2\" href=\"#\"><i class=\"bi bi-arrow-right text-primary me-2\"></i>Meet The Team</a>\n");
      out.write("                        <a class=\"text-body mb-2\" href=\"#\"><i class=\"bi bi-arrow-right text-primary me-2\"></i>Latest Blog</a>\n");
      out.write("                        <a class=\"text-body\" href=\"#\"><i class=\"bi bi-arrow-right text-primary me-2\"></i>Contact Us</a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-lg-3 col-md-6\">\n");
      out.write("                    <h5 class=\"text-uppercase border-start border-5 border-primary ps-3 mb-4\">Newsletter</h5>\n");
      out.write("                    <form action=\"\">\n");
      out.write("                        <div class=\"input-group\">\n");
      out.write("                            <input type=\"text\" class=\"form-control p-3\" placeholder=\"Your Email\">\n");
      out.write("                            <button class=\"btn btn-primary\">Sign Up</button>\n");
      out.write("                        </div>\n");
      out.write("                    </form>\n");
      out.write("                    <h6 class=\"text-uppercase mt-4 mb-3\">Follow Us</h6>\n");
      out.write("                    <div class=\"d-flex\">\n");
      out.write("                        <a class=\"btn btn-outline-primary btn-square me-2\" href=\"#\"><i class=\"bi bi-twitter\"></i></a>\n");
      out.write("                        <a class=\"btn btn-outline-primary btn-square me-2\" href=\"#\"><i class=\"bi bi-facebook\"></i></a>\n");
      out.write("                        <a class=\"btn btn-outline-primary btn-square me-2\" href=\"#\"><i class=\"bi bi-linkedin\"></i></a>\n");
      out.write("                        <a class=\"btn btn-outline-primary btn-square\" href=\"#\"><i class=\"bi bi-instagram\"></i></a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-12 text-center text-body\">\n");
      out.write("                    <a class=\"text-body\" href=\"\">Terms & Conditions</a>\n");
      out.write("                    <span class=\"mx-1\">|</span>\n");
      out.write("                    <a class=\"text-body\" href=\"\">Privacy Policy</a>\n");
      out.write("                    <span class=\"mx-1\">|</span>\n");
      out.write("                    <a class=\"text-body\" href=\"\">Customer Support</a>\n");
      out.write("                    <span class=\"mx-1\">|</span>\n");
      out.write("                    <a class=\"text-body\" href=\"\">Payments</a>\n");
      out.write("                    <span class=\"mx-1\">|</span>\n");
      out.write("                    <a class=\"text-body\" href=\"\">Help</a>\n");
      out.write("                    <span class=\"mx-1\">|</span>\n");
      out.write("                    <a class=\"text-body\" href=\"\">FAQs</a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"container-fluid bg-dark text-white-50 py-4\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row g-5\">\n");
      out.write("                <div class=\"col-md-6 text-center text-md-start\">\n");
      out.write("                    <p class=\"mb-md-0\">&copy; <a class=\"text-white\" href=\"#\">Your Site Name</a>. All Rights Reserved.</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-6 text-center text-md-end\">\n");
      out.write("                    <p class=\"mb-0\">Designed by <a class=\"text-white\" href=\"https://htmlcodex.com\">HTML Codex</a></p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <!-- Footer End -->\n");
      out.write("<!--  -->\n");
      out.write("  \n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
