/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.34
 * Generated at: 2023-11-23 08:59:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.ecommerce.pojo.*;
import com.ecommerce.dao.*;
import java.sql.*;
import java.util.*;

public final class myprofile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/components/common_cs_js.jsp", Long.valueOf(1698763001036L));
    _jspx_dependants.put("/components/navbar.jsp", Long.valueOf(1700729737544L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.ecommerce.pojo");
    _jspx_imports_packages.add("com.ecommerce.dao");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"ISO-8859-1\">\r\n");
      out.write("    <title>Profile - Precious Paw</title>\r\n");
      out.write("    <!-- Add your CSS and JS includes or links here -->\r\n");
      out.write("    ");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\" integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\"> \n");
      out.write("\n");
      out.write("<!-- JavaScript -->\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\" integrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\" integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\" integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\" crossorigin=\"anonymous\"></script>\n");
      out.write("\n");
      out.write("<script src=\"js/script.js\"></script>\n");
      out.write("\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        /* Add any additional styles here */\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

     User user=(User)session.getAttribute("active-user"); 

      out.write('\n');
      out.write('\n');

         CategoryDaoImp cdao=new CategoryDaoImp();
         List<Category> cl=cdao.getAllCategory();

      out.write("\n");
      out.write("<div class=\"container-fluid bg-dark py-3 px-lg-5 d-none d-lg-block\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <div class=\"col-md-6 text-center text-lg-left mb-2 mb-lg-0\">\n");
      out.write("                <div class=\"d-inline-flex align-items-center\">\n");
      out.write("                    <a class=\"text-body pr-3\" href=\"\"><i class=\"fa fa-phone-alt mr-2\"></i>+91 9030992019</a>\n");
      out.write("                    <span class=\"text-body\">|</span>\n");
      out.write("                    <a class=\"text-body px-3\" href=\"\"><i class=\"fa fa-envelope mr-2\"></i>2100090151csit@gmail.com</a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-6 text-center text-lg-right\">\n");
      out.write("                <div class=\"d-inline-flex align-items-center\">\n");
      out.write("                    <a class=\"text-body px-3\" href=\"https://facebook.com/freewebsitecode/\">\n");
      out.write("                        <i class=\"fab fa-facebook-f\"></i>\n");
      out.write("                    </a>\n");
      out.write("                    <a class=\"text-body px-3\" href=\"https://freewebsitecode.com/\">\n");
      out.write("                        <i class=\"fab fa-twitter\"></i>\n");
      out.write("                    </a>\n");
      out.write("                    <a class=\"text-body px-3\" href=\"https://freewebsitecode.com/\">\n");
      out.write("                        <i class=\"fab fa-linkedin-in\"></i>\n");
      out.write("                    </a>\n");
      out.write("                    <a class=\"text-body px-3\" href=\"https://freewebsitecode.com/\">\n");
      out.write("                        <i class=\"fab fa-instagram\"></i>\n");
      out.write("                    </a>\n");
      out.write("                    <a class=\"text-body pl-3\" href=\"https://youtube.com/freewebsitecode/\">\n");
      out.write("                        <i class=\"fab fa-youtube\"></i>\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write(" \n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark custom-bg\">\n");
      out.write("\n");
      out.write("<div class=\"container-fluid\">\n");
      out.write("  <a class=\"navbar-brand\" href=\"index.jsp\"><h3><i>Precious Paw</i></h3></a>\n");
      out.write("  <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("    <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("  </button>\n");
      out.write("\n");
      out.write("  <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("    <ul class=\"navbar-nav mr-auto\">\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    ");

         if(user!=null)
         {
        	 
        	 String userType=user.getUserType();
        	 if(userType.equals("admin"))
        	 {
    
      out.write("\n");
      out.write("                 <li class=\"nav-item active\">\n");
      out.write("                    <a class=\"nav-link\" href=\"admin.jsp\"><b>Admin Page</b> <span class=\"sr-only\">(current)</span></a>\n");
      out.write("                 </li>\n");
      out.write("    ");

        	 }
         }
    
      out.write("\n");
      out.write("      <li class=\"nav-item active dropdown\">\n");
      out.write("        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n");
      out.write("         <b> Categories</b>\n");
      out.write("        </a>\n");
      out.write("        <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\n");
      out.write("          <a class=\"dropdown-item\" href=\"index.jsp?category=0\" >All</a>\n");
      out.write("               ");

                    for(Category c: cl)
                    {    	
               
      out.write(" \n");
      out.write("                         <a class=\"dropdown-item\" href=\"index.jsp?category=");
      out.print(c.getCategoryId() );
      out.write('"');
      out.write('>');
      out.print(c.getCategoryTitle() );
      out.write("</a>     \n");
      out.write("               ");

                    }
               
      out.write("\n");
      out.write("          \n");
      out.write("        </div>\n");
      out.write("      </li>\n");
      out.write("      <li class=\"nav-item active ml-2\" data-toggle=\"modal\" data-target=\".contactusmodal\">\n");
      out.write("          <a href=\"index2.jsp\" class=\"nav-item nav-link\">Home</a>\n");
      out.write("      </li>\n");
      out.write("      <li class=\"nav-item active ml-2\" data-toggle=\"modal\" data-target=\".aboutusmodal\">\n");
      out.write("          <div class=\"nav-link\" ><b>About us</b></div>\n");
      out.write("      </li>\n");
      out.write("      \n");
      out.write("      <li class=\"nav-item active ml-2\">\n");
      out.write("    <a class=\"nav-link\" href=\"contact.jsp\"><b>Contact us</b></a>\n");
      out.write("</li>\n");
      out.write("      <li class=\"nav-item active ml-2\">\n");
      out.write("          <a class=\"nav-link\" href=\"services.jsp\"><b>Services</b></a>\n");
      out.write("      </li>\n");
      out.write("      <li class=\"nav-item active ml-2\">\n");
      out.write("          <a class=\"nav-link\" href=\"organization.jsp\"><b>Organizations</b></a>\n");
      out.write("      </li>\n");
      out.write("     \n");
      out.write("    </ul>\n");
      out.write("    \n");
      out.write("    <form class=\"form-inline my-2 my-lg-0\" action=\"ProductOperationServlet\" method=\"post\">\n");
      out.write("      <input type=\"hidden\" name=\"action\" value=\"searchProduct\">\n");
      out.write("      <input class=\"form-control mr-sm-2\" type=\"text\" placeholder=\"Search product\" aria-label=\"Search\" size=\"40\" name=\"search\">\n");
      out.write("      <button type=\"submit\" class=\"btn btn-light\" style=\"color:#ff9800\"><b>Search</b></button>\n");
      out.write("    </form>\n");
      out.write("    \n");
      out.write("    ");

        if(user!=null)
        {
        	  
    
      out.write("\n");
      out.write("    \n");
      out.write("          <ul class=\"navbar-nav ml-auto\">\n");
      out.write("              \n");
      out.write("              ");

                  if(user.getUserType().equals("normal"))
                  {
              
      out.write("\n");
      out.write("                     <li class=\"nav-item active\">\n");
      out.write("    <a class=\"nav-link\" href=\"mycart.jsp\">\n");
      out.write("        <img src=\"images/cart.png\" style=\"width:23px;\" alt=\"img\">\n");
      out.write("        (");
      out.print( new CartDaoImp().totalCartByUserId(user.getUserId()) );
      out.write(")\n");
      out.write("    </a>\n");
      out.write("</li>\n");
      out.write("                     \n");
      out.write("                     <li class=\"nav-item active\" data-toggle=\"modal\" data-target=\"#showmyordermodal\">\n");
      out.write("                        <a class=\"nav-link\" href=\"#\"><b>My Orders</b></a>\n");
      out.write("                     </li>\n");
      out.write("              ");

                  }
              
      out.write("\n");
      out.write("          \n");
      out.write("             <li class=\"nav-item active\">\n");
      out.write("    <a class=\"nav-link\" href=\"myprofile.jsp\"><b>");
      out.print( user.getUserName());
      out.write("</b></a>\n");
      out.write("</li>\n");
      out.write("             \n");
      out.write("             <li class=\"nav-item active\">\n");
      out.write("             <div class=\"nav-link\" data-toggle=\"modal\" data-target=\".changepasswordmodal\"><b>change password</b></div>\n");
      out.write("             </li>  \n");
      out.write("      \n");
      out.write("             <li class=\"nav-item active\" data-toggle=\"modal\" data-target=\".logout-modal\">\n");
      out.write("             <a class=\"nav-link\" href=\"#\" ><b>Logout</b></a>\n");
      out.write("             </li>    \n");
      out.write("         </ul>\n");
      out.write("   \n");
      out.write("    ");

        }
    
        else
        {
    
      out.write("\n");
      out.write("    <ul class=\"navbar-nav ml-auto\">\n");
      out.write("       <li class=\"nav-item active\">\n");
      out.write("        <div class=\"nav-link\" data-toggle=\"modal\" data-target=\".forgetpasswordmodal\"><b>Forget password</b></div>\n");
      out.write("      </li> \n");
      out.write("    \n");
      out.write("      <li class=\"nav-item active\">\n");
      out.write("        <a class=\"nav-link\" href=\"register.jsp\"><b>Register</b></a>\n");
      out.write("      </li>  \n");
      out.write("      \n");
      out.write("      <li class=\"nav-item active\">\n");
      out.write("        <a class=\"nav-link\" href=\"login.jsp\"><b>Login</b></a>\n");
      out.write("      </li>    \n");
      out.write("    </ul>\n");
      out.write("    \n");
      out.write("    ");

        }
    
      out.write("     \n");
      out.write("    \n");
      out.write("  </div>\n");
      out.write("  </div>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("<!-- show profile modal -->\n");
      out.write("\n");
      out.write("<div class=\"modal fade\" id=\"showprofilemodal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLongTitle\" aria-hidden=\"true\">\n");
      out.write("  <div class=\"modal-dialog modal-lg\" role=\"document\">\n");
      out.write("    <div class=\"modal-content\">\n");
      out.write("      <div class=\"modal-header custom-bg text-white text-center\">\n");
      out.write("        <h5 class=\"modal-title\" id=\"exampleModalLongTitle\" >MY PROFILE</h5>\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\n");
      out.write("        </button>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"modal-body\">\n");
      out.write("          <form >\n");
      out.write("         \n");
      out.write("         <div class=\"container text-center\">\n");
      out.write("                   <img style=\"max-width:200px\" class=\"img-fluid rounded-circle\" src=\"userProfilePic/");
if(user!=null){ 
      out.print(user.getUserPic() );
} 
      out.write("\" alt=\"users_pic\" >\n");
      out.write("         </div> \n");
      out.write("         \n");
      out.write("  <div class=\"form-row mt-3\">\n");
      out.write("    <div class=\"form-group col-md-4\">\n");
      out.write("      <label for=\"inputEmail4\">Name</label>\n");
      out.write("      <input type=\"text\" class=\"form-control\" id=\"inputEmail4\" value=\"");
if(user!=null){ 
      out.print(user.getUserName() );
} 
      out.write("\" readonly>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"form-group col-md-4\">\n");
      out.write("      <label for=\"inputPassword4\">Email</label>\n");
      out.write("      <input type=\"email\" class=\"form-control\" id=\"inputPassword4\" value=\"");
if(user!=null){ 
      out.print(user.getUserEmail() );
} 
      out.write("\" readonly>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"form-group col-md-4\">\n");
      out.write("      <label for=\"inputPassword4\">Phone</label>\n");
      out.write("      <input type=\"text\" class=\"form-control\" id=\"inputPassword4\" value=\"");
if(user!=null){ 
      out.print(user.getUserPhone() );
} 
      out.write("\" readonly>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("  <div class=\"form-group\">\n");
      out.write("    <label for=\"inputAddress\">Address</label>\n");
      out.write("    <textarea class=\"form-control\" id=\"inputAddress\" placeholder=\"1234 Main St\" rows=\"3\" readonly>");
if(user!=null){ 
      out.print(user.getUserAddress() );
} 
      out.write("</textarea>\n");
      out.write("  </div>\n");
      out.write(" \n");
      out.write("  <div class=\"container text-center\">\n");
      out.write("       <button type=\"button\" class=\"btn custom-bg text-light\" data-dismiss=\"modal\">Close</button>\n");
      out.write("  </div>   \n");
      out.write("</form>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!--  -->\n");
      out.write("\n");
      out.write("<!-- show my cart modal -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!--  -->\n");
      out.write("\n");
      out.write("<!-- show my order modal -->\n");
      out.write("\n");
      out.write("<div class=\"modal fade\" id=\"showmyordermodal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLongTitle\" aria-hidden=\"true\">\n");
      out.write("  <div class=\"modal-dialog modal-lg\" role=\"document\">\n");
      out.write("    <div class=\"modal-content\">\n");
      out.write("      <div class=\"modal-header custom-bg text-white text-center\">\n");
      out.write("        <h5 class=\"modal-title\" id=\"exampleModalLongTitle\" >MY ORDERS</h5>\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\n");
      out.write("        </button>\n");
      out.write("      </div>\n");
      out.write("     ");

      if(user!=null)
      {
    	  List<Order> l=new OrderDaoImp().getOrderByUserId(user.getUserId());
    	 
     
      out.write("\n");
      out.write("      <div class=\"modal-body\">\n");
      out.write("        \n");
      out.write("        ");

            if(l.isEmpty())
            {
        
      out.write("\n");
      out.write("        <div class=\"text-center\">\n");
      out.write("        <h1>NO ORDERS MADE BY YOU !!</h1>\n");
      out.write("        <hr>\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Close</button>\n");
      out.write("        </div>\n");
      out.write("        ");

            }
        
            else
            {
            	
            	
        
      out.write("\n");
      out.write("        <div class=\"table-responsive\">\n");
      out.write("          <table class=\"table\">\n");
      out.write("  <thead class=\"custom-bg text-white\">\n");
      out.write("    <tr>\n");
      out.write("      <th scope=\"col\">Product Image</th>\n");
      out.write("      <th scope=\"col\">Product Title</th> \n");
      out.write("      <th scope=\"col\">Product Description</th>    \n");
      out.write("      <th scope=\"col\">Quantity</th>\n");
      out.write("      <th scope=\"col\">Price</th>\n");
      out.write("      <th scope=\"col\">Ordered Date</th>\n");
      out.write("      <th scope=\"col\">Delivery Date</th>\n");
      out.write("    </tr>\n");
      out.write("  </thead>\n");
      out.write("  \n");
      out.write(" \n");
      out.write("  \n");
      out.write("  <tbody>\n");
      out.write("   ");

      OrderDaoImp odao=new OrderDaoImp();
      
   
      out.write("\n");
      out.write("  \n");
      out.write("   ");

      for(Order o:l)
      {
    	  int productId=o.getProdctId();
    	  Product p=new ProductDaoImp().getProductById(productId);
   
      out.write("\n");
      out.write("    <tr class=\"text-center\">\n");
      out.write("      <td><img style=\"max-height:100px;max-width:70px;width:auto;\" class=\"img-fluid mx-auto d-block\" src=\"productImages/");
      out.print(p.getProductPhoto() );
      out.write("\" alt=\"users_pic\" ></td>\n");
      out.write("      <td class=\"mid-align\">");
      out.print(p.getProductTitle() );
      out.write("</td>\n");
      out.write("      <td class=\"mid-align\">");
      out.print(p.getProductDescription() );
      out.write("</td>\n");
      out.write("      <td class=\"mid-align\">");
      out.print(o.getQuantity() );
      out.write("</td>\n");
      out.write("      <td class=\"mid-align\">");
      out.print(o.getPrice() );
      out.write("</td>\n");
      out.write("      <td class=\"mid-align\">");
      out.print(o.getOrderesDate() );
      out.write("</td>\n");
      out.write("      <td class=\"mid-align\">");
if(o.getDeliveryDate().equals("0")){ 
      out.write("<span style=\"color:red;\"> ");
      out.print("processing..");
      out.write("</span>    ");
} else { 
      out.write(' ');
      out.print(o.getDeliveryDate() );
} 
      out.write("</td>\n");
      out.write("    </tr>\n");
      out.write("    ");

      }
    
      out.write("\n");
      out.write("  </tbody>\n");
      out.write(" \n");
      out.write("  \n");
      out.write("</table>\n");
      out.write("<hr>\n");
      out.write("\n");
      out.write("<div class=\"text-right\">\n");
      out.write("    <p style=\"font-size:25px;\"><b>Total Price :&#8377;");
      out.print(new OrderDaoImp().totalOrderPrice(user.getUserId()) );
      out.write("/- </b></p> \n");
      out.write("</div>\n");
      out.write("<hr>\n");
      out.write("\n");
      out.write("      <button type=\"button\" class=\"btn btn-secondary ml-5\" data-dismiss=\"modal\">Close</button>\n");
      out.write("\n");
      out.write("       ");

            }
       
      out.write("\n");
      out.write("         \n");
      out.write("      </div>\n");
      out.write("  ");

           
      }
  
      out.write("\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!--  -->\n");
      out.write("\n");
      out.write("<!-- Logout modal -->\n");
      out.write("\n");
      out.write("<div class=\"modal fade logout-modal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"mySmallModalLabel\" aria-hidden=\"true\">\n");
      out.write("  <div class=\"modal-dialog modal-sm\">\n");
      out.write("    <div class=\"modal-content\">\n");
      out.write("    <div class=\"modal-header custom-bg text-white text-center\">\n");
      out.write("        <h5 class=\"modal-title\" id=\"exampleModalLongTitle\" >Log Out</h5>\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\n");
      out.write("        </button>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"modal-body text-center\">\n");
      out.write("            <h5>Do you want to logout?</h5>\n");
      out.write("          \n");
      out.write("          <div class=\"text-center\">\n");
      out.write("            <a href=\"LoginServlet\"><button type=\"button\" class=\"btn custom-bg text-white\">Yes</button></a>\n");
      out.write("            <button type=\"button\" class=\"btn btn-secondary ml-5\" data-dismiss=\"modal\">No</button>\n");
      out.write("          </div> \n");
      out.write("     </div>     \n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!-- *********** -->\n");
      out.write("\n");
      out.write("<!-- About us modal -->\n");
      out.write("\n");
      out.write("<div class=\"modal fade aboutusmodal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"mySmallModalLabel\" aria-hidden=\"true\">\n");
      out.write("  <div class=\"modal-dialog modal-lg\">\n");
      out.write("    <div class=\"modal-content\">\n");
      out.write("       <div class=\"modal-header custom-bg text-white text-center\">\n");
      out.write("        <h5 class=\"modal-title\" id=\"exampleModalLongTitle\" >About Us</h5>\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\n");
      out.write("        </button>\n");
      out.write("      </div> \n");
      out.write("      <div class=\"modal-body\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("        <p style=\"font-size:20px;\">\n");
      out.write("          <b>\n");
      out.write("              Welcome to our pet-centric platform! A pet website is a virtual haven where you can explore a world dedicated to the well-being, trade, and interactions involving our beloved furry companions.\n");
      out.write("\n");
      out.write("Pets, from our loyal dogs to our enchanting cats, bring immense joy to our lives. This website celebrates the beauty of pet ownership, offering avenues for the exchange of services, information, and connections within the pet-loving community.\n");
      out.write("\n");
      out.write("Just like the age-old barter system and trade that has been a part of human history, pet enthusiasts and owners have always sought ways to connect and provide for their furry friends. Whether it's pet services, sharing pet-related knowledge, or finding that perfect toy, our platform facilitates this exchange.\n");
      out.write("\n");
      out.write("Transactions, both locally and globally, have been the backbone of the pet community. Now, in the digital realm, we embrace this legacy, creating a space where pet lovers can come together, trade, and seek services.\n");
      out.write("\n");
      out.write("However, as we step into the digital sphere, we're acutely aware of the importance of data privacy. Stringent data protection laws govern our operations. Prior to engaging in our pet-oriented venture, it's crucial to understand and comply with all the legal policies necessary to safeguard the data and privacy of our users.\n");
      out.write("\n");
      out.write("Our pet-centric platform aims to merge the joy of pet ownership with a secure, user-friendly online experience, fostering a community that values the love and care for our adorable companions.\n");
      out.write("          </b>\n");
      out.write("        </p>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"modal-footer\">\n");
      out.write("       <div class=\"text-center\">\n");
      out.write("        <button type=\"button\" class=\"btn custom-bg text-white\" data-dismiss=\"modal\">Close</button>\n");
      out.write("       </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("<!-- ********** -->\n");
      out.write("\n");
      out.write("<!-- Contact us modal -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- change password modal -->\n");
      out.write("\n");
      out.write("<div class=\"modal fade changepasswordmodal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLongTitle\" aria-hidden=\"true\">\n");
      out.write("  <div class=\"modal-dialog\" role=\"document\">\n");
      out.write("    <div class=\"modal-content\">\n");
      out.write("      <div class=\"modal-header custom-bg text-white text-center\">\n");
      out.write("        <h5 class=\"modal-title\" id=\"exampleModalLongTitle\" >Change Password</h5>\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\n");
      out.write("        </button>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"modal-body\">\n");
      out.write("          <form action=\"LoginServlet\" method=\"post\">\n");
      out.write("          <input type=\"hidden\" name=\"action\" value=\"changePassword\">\n");
      out.write("         \n");
      out.write("  <div class=\"form\">\n");
      out.write(" \n");
      out.write("    <div class=\"form-group \">\n");
      out.write("      <label for=\"inputPassword4\">Email</label>\n");
      out.write("      <input type=\"email\" class=\"form-control\" id=\"inputPassword4\" value=\"");
if(user!=null){ 
      out.print(user.getUserEmail() );
} 
      out.write("\" readonly>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"form-group\">\n");
      out.write("      <label for=\"inputPassword4\">Password</label>\n");
      out.write("      <input type=\"password\" class=\"form-control\" id=\"pass\" name=\"pass\" >\n");
      out.write("    </div>\n");
      out.write("    <div class=\"form-group\">\n");
      out.write("      <label for=\"inputPassword4\">Confirm Password</label>\n");
      out.write("      <input type=\"password\" class=\"form-control\" id=\"cpass\" name=\"cpass\">\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write(" \n");
      out.write("  <div class=\"container text-center\">\n");
      out.write("       \n");
      out.write("       <input type=\"submit\" class=\"btn custom-bg text-light\" value=\"Change\">\n");
      out.write("       <button type=\"button\" class=\"btn custom-bg text-light ml-5\" data-dismiss=\"modal\">Close</button>\n");
      out.write("                                      \n");
      out.write("  </div>   \n");
      out.write("</form>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!--  -->\n");
      out.write("\n");
      out.write("<!-- forget password modal -->\n");
      out.write("\n");
      out.write("<div class=\"modal fade forgetpasswordmodal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLongTitle\" aria-hidden=\"true\">\n");
      out.write("  <div class=\"modal-dialog\" role=\"document\">\n");
      out.write("    <div class=\"modal-content\">\n");
      out.write("      <div class=\"modal-header custom-bg text-white text-center\">\n");
      out.write("        <h5 class=\"modal-title\" id=\"exampleModalLongTitle\" >Forget Password</h5>\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\n");
      out.write("        </button>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"modal-body\">\n");
      out.write("          <form action=\"LoginServlet\" method=\"post\">\n");
      out.write("          <input type=\"hidden\" name=\"action\" value=\"forgetPassword\">\n");
      out.write("         \n");
      out.write("  <div class=\"form\">\n");
      out.write(" \n");
      out.write("    <div class=\"form-group \">\n");
      out.write("      <label for=\"inputPassword4\">Email</label>\n");
      out.write("      <input type=\"email\" class=\"form-control\" id=\"email\" name=\"email\">\n");
      out.write("    </div>\n");
      out.write("    <div class=\"form-group \">\n");
      out.write("      <label for=\"inputPassword4\">Phone</label>\n");
      out.write("      <input type=\"text\" class=\"form-control\" id=\"phone\" name=\"phone\">\n");
      out.write("    </div>\n");
      out.write("    <div class=\"form-group\">\n");
      out.write("      <label for=\"inputPassword4\">Password</label>\n");
      out.write("      <input type=\"password\" class=\"form-control\" id=\"pass\" name=\"pass\" >\n");
      out.write("    </div>\n");
      out.write("    <div class=\"form-group\">\n");
      out.write("      <label for=\"inputPassword4\">Confirm Password</label>\n");
      out.write("      <input type=\"password\" class=\"form-control\" id=\"cpass\" name=\"cpass\">\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write(" \n");
      out.write("  <div class=\"container text-center\">\n");
      out.write("       \n");
      out.write("       <input type=\"submit\" class=\"btn custom-bg text-light\" value=\"Change\">\n");
      out.write("       <button type=\"button\" class=\"btn custom-bg text-light ml-5\" data-dismiss=\"modal\">Close</button>\n");
      out.write("                                      \n");
      out.write("  </div>   \n");
      out.write("</form>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!--  -->\n");
      out.write("\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"modal-dialog modal-lg\" role=\"document\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header custom-bg text-white text-center\">\r\n");
      out.write("                <h5 class=\"modal-title\">MY PROFILE</h5>\r\n");
      out.write("                <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                    <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("                <form>\r\n");
      out.write("                    <div class=\"container text-center\">\r\n");
      out.write("                        <img style=\"max-width:200px\" class=\"img-fluid rounded-circle\" src=\"userProfilePic/");
if(user!=null){ 
      out.print(user.getUserPic() );
} 
      out.write("\" alt=\"users_pic\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-row mt-3\">\r\n");
      out.write("                        <div class=\"form-group col-md-4\">\r\n");
      out.write("                            <label for=\"inputEmail4\">Name</label>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" id=\"inputEmail4\" value=\"");
if(user!=null){ 
      out.print(user.getUserName() );
} 
      out.write("\" readonly>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group col-md-4\">\r\n");
      out.write("                            <label for=\"inputPassword4\">Email</label>\r\n");
      out.write("                            <input type=\"email\" class=\"form-control\" id=\"inputPassword4\" value=\"");
if(user!=null){ 
      out.print(user.getUserEmail() );
} 
      out.write("\" readonly>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group col-md-4\">\r\n");
      out.write("                            <label for=\"inputPassword4\">Phone</label>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" id=\"inputPassword4\" value=\"");
if(user!=null){ 
      out.print(user.getUserPhone() );
} 
      out.write("\" readonly>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"inputAddress\">Address</label>\r\n");
      out.write("                        <textarea class=\"form-control\" id=\"inputAddress\" placeholder=\"1234 Main St\" rows=\"3\" readonly>");
if(user!=null){ 
      out.print(user.getUserAddress() );
} 
      out.write("</textarea>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Add more form fields as needed -->\r\n");
      out.write("                    <div class=\"form-row mt-3\">\r\n");
      out.write("                        <!-- Add more form fields here -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"container text-center\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn custom-bg text-light\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("                    </div>   \r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
